version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    volumes:
      - ./services/users:/usr/src/app
    ports:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:2v#fli0RmdbCNlZ1@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:2v#fli0RmdbCNlZ1@users-db:5432/users_test
    depends_on:
      - users-db

  client-admin:
    build:
      context: ./client-admin
      dockerfile: Dockerfile-prod
    volumes:
      - ./client-admin:/usr/src/app
      - ./client-admin/src:/usr/src/app/src
      - ./client-admin/config:/usr/src/app/config
      - ./client-admin/mock:/usr/src/app/mock
      - dist:/usr/src/app/dist
      - /usr/src/app/node_modules
      - dist:/usr/share/nginx/html:ro
    ports:
      - 8001:80
    environment:
      - NODE_ENV=production
      #- REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - CHOKIDAR_USEPOLLING=true # enable hot reloading
    depends_on:
      - users

  # client:
  #   build:
  #     context: ./services/client
  #     dockerfile: Dockerfile-dev
  #   volumes:
  #     - './services/client:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - 3007:3000
  #   environment:
  #     - NODE_ENV=production
  #     - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
  #     - CHOKIDAR_USEPOLLING=true # enable hot reloading
  #   depends_on:
  #     - users

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2v#fli0RmdbCNlZ1
      #- POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client-admin
      #- client

volumes:
  dist: